[project]
name = "pdf-to-audio"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "gtts>=2.5.4",
    "pdfplumber>=0.11.7",
    "pymupdf>=1.26.4",
    "pyttsx3>=2.99",
]
